CREATE TABLE CATEGORY (
    CATEGORY_ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE FUNDRAISER (
    FUNDRAISER_ID INT AUTO_INCREMENT PRIMARY KEY,
    ORGANIZER VARCHAR(255),
    CAPTION TEXT,
    TARGET_FUNDING DECIMAL(10, 2),
    CURRENT_FUNDING DECIMAL(10, 2),
    CITY VARCHAR(255),
    ACTIVE BOOLEAN,
    CATEGORY_ID INT,
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID)
);

INSERT INTO CATEGORY (NAME) 
VALUES 
('Medical'), 
('Education'), 
('Social Impact');

INSERT INTO FUNDRAISER (ORGANIZER, CAPTION, TARGET_FUNDING, CURRENT_FUNDING, CITY, ACTIVE, CATEGORY_ID) 
VALUES 
('The Ahmetaj Family', 'Support Milena\'s Fight Against Leukemia', 300000, 150000, 'Sarasota, FL', 1, 1);

